### ISSUE TITLE
1.18 port

### ISSUE THREAD

**Issue by Technici4n** [Draylar/magna#21]
Hi @Draylar, it would be nice if you could port Magna to 1.18 so that dependent mods could also port. :)

**Comment by Draylar** [comment]
Out on JitPack & tested locally; please let me know if anything breaks!

```groovy
maven { url 'https://jitpack.io' }
```

```groovy
modImplementation 'com.github.Draylar:magna:1.7.0-1.18'
```

**Comment by Technici4n** [comment]
Seems to work perfectly, thanks! :)
