### ISSUE TITLE
It is that time again

### ISSUE THREAD

**Issue by Technici4n** [Draylar/magna#23]
Hi @Draylar, hope you're doing well on your no Discord break! Can I request a 1.19 update? :)

**Comment by Technici4n** [comment]
Ported here: https://github.com/Technici4n/magna. Feel free to just pull my commits to your repo.

Others: you can use `1.8.1-1.19` from my own repo in the meanwhile. :)

**Comment by MJRamon** [comment]
> Ported here: https://github.com/Technici4n/magna. Feel free to just pull my commits to your repo.
> 
> Others: you can use `1.8.1-1.19` from my own repo in the meanwhile. :)

Can you also update it for 1.19.1, or does it work as is? Thanks!

**Comment by Technici4n** [comment]
Closing due to #25.
